### ISSUE TITLE
Can't run get_match_info

### ISSUE THREAD

**Issue by santafebound** [fbessez/Tinder#10]
I'm trying to execute the following function:

`python -c 'import features; print(features.get_match_info())'`

But I get this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\tinder-script\features.py", line 19, in get_match_info
    matches = api.get_updates()['matches']
KeyError: 'matches'

```

Am I missing a parameter in the function execution?

I noticed also that when I run the curl command to get updates, there is an error:

```
$ curl -i -X POST \
>             -H "X-Auth-Token: some-x-auth-token" \
>             -H "Content-type: application/json" \
>             -H "User-agent: Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)" \
>     https://api.gotinder.com/updates
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    42  100    42    0     0     65      0 --:--:-- --:--:-- --:--:--    67HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Thu, 14 Sep 2017 08:44:55 GMT
X-Request-ID: some-x-request-id
Content-Length: 42
Connection: keep-alive

{"status":400,"error":"malformed request"}

```

The same X-Auth-Token works for other GET commands, so that shouldn't be the issue. What's going on here?

**Comment by fbessez** [comment]
Perhaps you do not have any matches, and so the key does not exist? I just ran it on my computer and it seems to be working fine. 
Maybe Tinder was not working momentarily?
I run it with python3 so perhaps there is a subtle difference there as well.
Let me know if any of those are possibilities

**Comment by santafebound** [comment]
Hey,

I have matches in the app itself. I went through the steps to get my X-Auth-Token from my Facebook Access Token so I can only assume they're connected. Get Recs and Profile work fine with the same token so I figure my curl command could be incorrect. But running the Python script doesn't seem to work either. I'm using Python3 as well and used the proper print notation, i.e. print() instead of print for Python2.

Maybe I'm not executing the command correctly?

``python -c 'import features; print(features.get_match_info())'``

**Comment by fbessez** [comment]
Hmm, I just ran what you suggested and got the same error. 
Perhaps you have to import the api file as well because I figure api.get_updates() isn't returning anything.

**Comment by santafebound** [comment]
I'm using ``Python 3.6.2``.

I see that get_match_info calls get_updates so I tried calling get_updates by itself:

python -c 'import tinder_api; print(tinder_api.get_updates("2017-07-09T10:28:13.392Z"))'

The result is:

``$ python -c 'import tinder_api; print(tinder_api.get_updates("2017-07-09T10:28:13.392Z"))'
{'status': '401', 'error': ''}``

A 401 status code generally means Unauthorized Access. So I'm not sure what to make of this. The matches may been returned empty because I'm not authorized to get updates from Tinder using this particular call...

**Comment by santafebound** [comment]
Using ``python3 -i features.py`` worked (presumably ``python.exe - features.py`` on Windows), but I get the following:

```
You have been successfully authorized!
Gathering Data on your matches...
An exception of type KeyError occurred. Arguments:
('bio',)
An exception of type KeyError occurred. Arguments:
('bio',)
An exception of type KeyError occurred. Arguments:
('bio',)
All data stored in: match_info
```

And I can't see any file called ``match_info``.

**Comment by santafebound** [comment]
Ohhh. I get it. I typed ``match_info`` into the interactive shell. And there, returned the correct JSON.

**Comment by fbessez** [comment]
BOOM! yea, the exceptions are for some of the matches that do not have a bio.

**Comment by santafebound** [comment]
Cheers. Thanks for the help! Have you heard of https://betalist.com/startups/gitkeep? This is exactly the kind of repo that many developers would pay to support I believe.

**Comment by Frontstriker15** [comment]
Now I have the same Problem within the like function...
`tinder_api.like(res['_id'])`

My output looks like the same as @SeloSlav 's
> {'status': 400, 'error': 'malformed request'}

Found this issue to my problem:
[look here](https://github.com/jaebradley/tinder-client/issues/76)
