### ISSUE TITLE
Any recent changes to the API?

### ISSUE THREAD

**Issue by elmanko** [fbessez/Tinder#106]
Just tested it right now and I cannot get all_matches() to work and also tried re-auth with the phone_auth_token, looks like is no longer working, were there any changes to the api? 
It was working just fine yesterday...

**Comment by RMatushkin** [comment]
@elmanko  You can check my Java implementation of Tinder API, there you can find authorization via SMS and other endpoints. Even I described how to sniff traffic on the Android platform. Welcome! 🙂
https://github.com/RMatushkin/tinder-api

**Comment by elmanko** [comment]
got fixed by https://github.com/fbessez/Tinder/pull/117 
shout-out to @jimtje

**Comment by jimtje** [comment]
I think they've gone full gRPC (although they've also left some backwards compatible stuff in the code so it requires a bit of further inquiry). The raw .proto files are https://gitee.com/auf/tinder-grpc-exploration

**Comment by gelodefaultbrain** [comment]
> @elmanko You can check my Java implementation of Tinder API, there you can find authorization via SMS and other endpoints. Even I described how to sniff traffic on the Android platform. Welcome! 🙂 https://github.com/RMatushkin/tinder-api

Hi , page is not found, was there any changes?
