### ISSUE TITLE
'avg_successRate': 0.7837966008217391

### ISSUE THREAD

**Issue by panderlad** [fbessez/Tinder#127]
what this means?

**Comment by Binj0** [comment]
Where did you find that?

**Comment by panderlad** [comment]
> 
> 
> Where did you find that?

 Sorting:
Sorting matches by "age", "message_count", and "gender"

[
	  ('123456789123456789',
	  {
	    'messages': [

	    ],
	    'age': 19,
	    'match_id': '123456789123456789abcdefghi',
	    'name': 'Carmelo',
	    'photos': [
	      'http://images.gotinder.com/123456789123456789.jpg',
	      'http://images.gotinder.com/123456789123456789.jpg',
	      'http://images.gotinder.com/123456789123456789.jpg',
	      'http://images.gotinder.com/123456789123456789.jpg'
	    ],
	    'message_count': 0,
	    'last_activity_date': '0 days, 22 hrs 23 min 45 sec',
	    'ping_time': '2017-03-25T23:22:08.954Z',
	    'gender': 1,
	    'bio': 'I do not like to win sometimes', 'avg_successRate': 0.7837966008217391
	    }
	    )

**Comment by Binj0** [comment]
Thats weird, your response body looks pretty different to mine. Why aren't the Tinder-Images like: https://images-ssl.gotinder.com/. At least thats how they appear on my matches request. Concerning the successRate, I don't know either sry.

**Comment by panderlad** [comment]
> 
> 
> Thats weird, your response body looks pretty different to mine. Why aren't the Tinder-Images like: https://images-ssl.gotinder.com/. At least thats how they appear on my matches request. Concerning the successRate, I don't know either sry.

I copied that text from the homepage of this project.

**Comment by Binj0** [comment]
Ah I see, I guess this is deprecated. The response doesn't contain that value anymore
