### ISSUE TITLE
Updating age filter, with https://api.gotinder.com/v2/profile or  https://api.gotinder.com/profile?

### ISSUE THREAD

**Issue by panderlad** [fbessez/Tinder#129]
I try to update the age filter, and it works only with first version of Tinder API, this link, https://api.gotinder.com/profile, if i use version2, (https://api.gotinder.com/v2/profile), i get 200 status response, but the filter it's not change in the profile, so i'm wondering if using the first version of API is somehow prejudicial on the tinder profile used or not,

 and if there is a way to make it works on V2.
 
 thanks

This is the code i send
{
"age_filter_min": 23,
"age_filter_max": 23
}

**Comment by Binj0** [comment]
Maybe try:

`{
"user":
{
"age_filter_min": 23,
"age_filter_max": 23
}
}`

**Comment by panderlad** [comment]
thanks
