### ISSUE TITLE
Fb Authentication

### ISSUE THREAD

**Issue by josephshawcroft** [fbessez/Tinder#14]
I'm having trouble getting the fb id and access token so I can utilise the Tinder API. I've tried running the config python script (I get a ModuleNotFound error regarding 'requests' on fb_auth_token.py. I've also tried looking manually via fb for developers but I'm having no luck. The authentication process from Facebook -> Tinder seems quite unclear to me.

Does anyone have a reproducible surefire step by step guide of getting their id/access token AND it passes tinder authentication? It would be very much appreciated.

Thanks

**Comment by HEATH3N** [comment]
Sure, you can find your ID by pasting your Facebook profile URL [here](https://findmyfbid.in). Alternatively, you can view the Network tab of F12 tools, go to your Facebook profile, and look for a param starting with `10000`.

As for the token, with Network still visible, you can click [here](https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&display=touch&state=%7B%22challenge%22%3A%22IUUkEUqIGud332lfu%252BMJhxL4Wlc%253D%22%2C%220_auth_logger_id%22%3A%2230F06532-A1B9-4B10-BB28-B29956C71AB1%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&default_audience=friends&return_scopes=true&auth_type=rerequest&client_id=464891386855067&ret=login&sdk=ios&logger_id=30F06532-A1B9-4B10-BB28-B29956C71AB1&ext=1470840777&hash=AeZqkIcf-NEW6vBd) and view the token from the OAuth confirmation. Unfortunately, this is a short-lived token (two hours I think?) but you can get a longer one (60 days IIRC) by using Charles Proxy or a similar tool to sniff the traffic from your phone.

**Comment by fbessez** [comment]
Hey, if 'requests' is not found then you probably have to run `pip install requests` or something like that. You don't need to be concerned with the fb_id and access_token because my script deals with that for you if you just give it your fb username and password

**Comment by fbessez** [comment]
Also '''
the url to get your fb_auth_token
https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&display=touch&state=%7B%22challenge%22%3A%22IUUkEUqIGud332lfu%252BMJhxL4Wlc%253D%22%2C%220_auth_logger_id%22%3A%2230F06532-A1B9-4B10-BB28-B29956C71AB1%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&default_audience=friends&return_scopes=true&auth_type=rerequest&client_id=464891386855067&ret=login&sdk=ios&logger_id=30F06532-A1B9-4B10-BB28-B29956C71AB1&ext=1470840777&hash=AeZqkIcf-NEW6vBd
When you go to this url, you will be asked to allow tinder access to your facebook
Presumably, this has already been done. Before pressing 'ok',
Open up the Developer Tools in Chrome by going View -> Developer -> Developer Tools
Here, you will see a series of tabs, one of which will be 'Networks'
Click on this.
On the Name sidebar there should be one that begins with 'confirm?dpr='
Click on that.
Now there should be a tab that says "Response" inside of which will begin
with: for (;;); {"..."}. In this response, there will be a part that says
"access_token=<access_token>&expires"
Copy and Paste that <access_token> below where <fb_token> is written
I am working on getting this fb_token programmatically
the url to get your fb_user_id
http://findmyfbid.com/
'''

fb_auth_token = <fb_token>
fb_user_id = <id>

**Comment by dhananjaykulkarni19** [comment]
Thanks a lot . You saved me from frustration. I have been trying to access Tinder API with Facebook Android SDK since many days but it is not accpeting the access token and was throwing
 
{"code":500,"error":"Error calling Facebook: FB API Error HTTP status code: 400. Error message: (#12) bio field is deprecated for versions v2.8 and higher. Error code: undefined @lib/facebookClient.makeRequest#FB_UNKNOWN","error_no":50014}

But above trick saved my ass. Access token obtained with above trick works for me now I tried hardcoding it in the android app for now and it works like a chram. But how can I achieve this generecally ..? Awaiting your response.

**Comment by lvkv** [comment]
When calling `get_self()` I get `JSONDecodeError("Expecting value", s, err.value) from None` (presumably because nothing is returned). However, when I wrap this in a block like so:
```
if authverif():
    print(get_self())
```
I just get back the output `'token'`. I'm also getting  `{'status': 401, 'error': ''}` when using `get_recommendations()` so I feel like it's an access thing. Fb creds are working, and no errors thrown in Fb token or id functions. Am I missing something?

**Comment by nathandaly** [comment]
@fbessez I am trying to use your repo as an example to build an Electron version. If I authentication with my own fb app then tinder auth returns
```
{"code":500,"error":"Error calling Facebook: FB API Error HTTP status code: 400. Error message: (#12) bio field is deprecated for versions v2.8 and higher. Error code: undefined @lib/facebookClient.makeRequest#FB_UNKNOWN","error_no":50014}
```

You're link using the tinder SSO does not redirect anywhere, I listen for a redirect event and grab the token from the new url returned. Do you know how to trigger a redirect using that link or a way to programmatically get the access token?
