### ISSUE TITLE
An exception of type KeyError occurred. Arguments:

### ISSUE THREAD

**Issue by reiyaono** [fbessez/Tinder#15]
hi, I have a question.

I think I can't gether the data exactly.
 ```
python -i features.py
You have been successfully authorized!
Gathering Data on your matches...
An exception of type KeyError occurred. Arguments:
('bio',)
An exception of type KeyError occurred. Arguments:
('bio',)
.....

```

How can I fix it?

**Comment by fbessez** [comment]
Hey @reiyaono, this isn't actually an error. 

It is just an exception. So basically, at this point in the code, the program is checking to see that each of your matches has a 'bio' field in the data returned. Some users do not have the 'bio' field and therefore an exception occurs. Just ignore it. If you would like for this to go away, just comment out lines 40-42 in features.py and replace them with `pass`
