### ISSUE TITLE
An example of using the API?

### ISSUE THREAD

**Issue by ghost** [fbessez/Tinder#2]
Hi!

I managed to get a successful authentication by running the command 'python run.py' in terminal, but not quite sure on how to proceed further. I was wondering as to whether you could kindly provide an example (like getting your profile info) of code?

Apologies for the very newbie question (zero knowledge of programming here).

**Comment by fbessez** [comment]
Hey, sorry. Just saw this. I will post one soon, is there something that you would like to know in particular, or is getting profile what you want?

**Comment by fbessez** [comment]
ok first run:
`python3 -i run.py`
This will let you interact(-i) with the code after it's compiled.
At this point, it should indicate that you've successfully gotten your auth token and stored your match info in match_info.

Then if you want to see your profile, you'd then type in where it says >>> in the terminal
`api.get_self()` which will return something like 
```json
{
  '_id': '588a824a73564ae27e84f8f8',
  'can_create_squad': True,
  'bio': '🇫🇷 🇨🇱 Fabien is from New York City and enjoys video games, basketball, and listening to Ariana Grande. In his free time, he works on developing a web app for Tinder, a popular lifestyle application for mobile devices.',
  'pos_info': {
    'state': {
      'bounds': {
        'ne': {
          'lat': 45.015865,
          'lng': -71.777491
        },
        'sw': {
          'lat': 40.477399,
          'lng': -79.76259
        }
      },
      'name': 'New York'
    },
    'country': {
      'bounds': {
        'ne': {
          'lat': 72.781306,
          'lng': 180
        },
        'sw': {
          'lat': 15.265251,
          'lng': -180
        }
      },
      'cc': 'US',
      'name': 'United States'
    },
    'city': {
      'bounds': {
        'ne': {
          'lat': 40.917577,
          'lng': -73.00000000
        },
        'sw': {
          'lat': 40.00000,
          'lng': --74.00000
        }
      },
      'name': 'New York'
    }
  },
  'interested_in': [
    1
  ],
  'discoverable': True,
  'gender_filter': 1,
  'distance_filter': 3,
  'jobs': [
    
  ],
  'squads_only': False,
  'age_filter_max': 25,
  'gender': 1,
  'ping_time': '2017-03-26T23:05:00.773Z',
  'age_filter_min': 20,
  'pos': {
    'lon': -73.00000000000,
    'lat': 40.0000000000000,
    'at': 1490476676273
  },
  'create_date': '2017-01-26T23:12:09.859Z',
  'squads_discoverable': True,
  'location': None,
  'schools': [
    {
      'year': '2015',
      'displayed': True,
      'name': 'Vassar College',
      'type': 'College',
      'id': '40043952139'
    },
    {
      'year': '',
      'displayed': True,
      'name': 'Wesleyan University',
      'type': 'College',
      'id': '29396949994'
    }
  ],
  'blend': 'optimal',
  'name': 'Fabien',
  'birth_date': '1995-12-11T00:00:00.000Z',
  'facebook_id': '1234556789',
  'squad_ads_shown': True
}
```
if you want you could store it in a variable by typing `my_data = api.get_self()`
then, if you want to access your bio you'd type `my_data['bio']`

Let me know if you have any other questions 👍

**Comment by gavingimbo** [comment]
Hi!

Thank you very much for your reply and the provided information.

I went ahead and executed the get_self() function and it worked well (but my output is all written in one line, not organized as you've shown, I think that's normal?).

One last command I'd like to know is in retrieving match info. I tried issuing the command match_info() but got this: {}.

Would appreciate your support on it. Thanks again!

**Comment by fbessez** [comment]
Hey again,

Yeah, it should all come out in one line. There are Chrome plug-ins and terminal commands that you can help 'prettify' the JSON that is returned. 

Also, for the match_info thing that you're speaking about. The data should already be stored in a variable called match_info.  So instead of writing `match_info()` you'd just type in `match_info`. If you want to run it yourself you'd have to type in `get_match_info()`

**Comment by gavingimbo** [comment]
Understood!

I did match_info and it still showed {} as a result. Doesn't show me info of my existing matches.

Also to make sure, I ran get_match_id_by_name('Alex'), the result showed as there were no matches by that person's name.

**Comment by fbessez** [comment]
Strange, are you sure you logged in with the correct Facebook information in the config file?

**Comment by gavingimbo** [comment]
Yes! I, in fact, cloned the repo again to make sure. I tried a combination of my facebook username/password and email/password. All seem to return the empty {} output.

I do have one existing match, and I also tried `friends_pingtimes()` which worked just fine so I believe the account is properly connected.

**Comment by fbessez** [comment]
ok, sweet. What version of python are you running on? Maybe there is an issue with the python version compatibility? I am testing it on Python 3.5.2. Is that what you are using as well? 
Sorry, I'm not being incredibly helpful.

**Comment by gavingimbo** [comment]
I use the latest Python version (3.6.1) for Windows. I tried with Ubuntu too, but the same occurs. Downgraded to Python 3.5.2.

Upon fresh install, I always install the modules that it shows are missing, and those are:

```
- requests
- robobrowser
- lxml
```

**Comment by fbessez** [comment]
I have no clue. I'm sorry I can't help. No idea what's wrong. Let me know if you figure it out!

**Comment by gavingimbo** [comment]
Will do. Thank you very much for your time and effort in helping me! :)

**Comment by fbessez** [comment]
Run.py was renamed to features.py
