### ISSUE TITLE
Response [403] When api.authverif()

### ISSUE THREAD

**Issue by drawalex** [fbessez/Tinder#22]
I'm getting a Response [403] when trying to api.authverif() i also get Expecting value: line 1 column 1 (char 0)

any help would be greatly appreciated.

**Comment by fbessez** [comment]
did you set up your config file?

**Comment by drawalex** [comment]
Yeah I tested it by running config.fb_access_token("USERNAME","PASS") and it returned a token

**Comment by fbessez** [comment]
Strange, it works well for me. Maybe send some more details about how you're set up? Are you using python3?

**Comment by fbessez** [comment]
Do you have a tinder account already?

**Comment by drawalex** [comment]
Yeah ive worked it out now. I was using a VPN on my pc turned it off and it worked
