### ISSUE TITLE
BadRequestKeyError from fb_auth_token.py

### ISSUE THREAD

**Issue by JordieB** [fbessez/Tinder#23]
I'm trying to run the following function on the correct email address and password:

```python
import re

import requests
import robobrowser

MOBILE_USER_AGENT = "{personal_UA}"
FB_AUTH = "https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&display=touch&state=%7B%22challenge%22%3A%22IUUkEUqIGud332lfu%252BMJhxL4Wlc%253D%22%2C%220_auth_logger_id%22%3A%2230F06532-A1B9-4B10-BB28-B29956C71AB1%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22sfvc_auth%22%7D&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&default_audience=friends&return_scopes=true&auth_type=rerequest&client_id=464891386855067&ret=login&sdk=ios&logger_id=30F06532-A1B9-4B10-BB28-B29956C71AB1&ext=1470840777&hash=AeZqkIcf-NEW6vBd"


def get_fb_access_token(email, password):
    s = robobrowser.RoboBrowser(user_agent=MOBILE_USER_AGENT, parser="lxml")
    s.open(FB_AUTH)
    f = s.get_form()
    f["pass"] = password
    f["email"] = email
    s.submit_form(f)
    f = s.get_form()
    s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])
    access_token = re.search(
        r"access_token=([\w\d]+)", s.response.content.decode()).groups()[0]
    return access_token
```

However, I get the following error:

>BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

The traceback points back:

> 18     s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])

[After doing a bit of research](https://stackoverflow.com/questions/42575421/robobrowser-form-submission), it seems `submit=f.submit_fields['__CONFIRM__'])` can be changed to `submit='__CONFIRM__'`. However, the response.content doesn't include the access_token but instead I see more of the bad requests:

>[...]badRequestKeys:["nonce","access_token","oauth_token","xs"][...]

Thoughts? Does it only not work for me or something?

**Comment by fbessez** [comment]
Maybe it has to do with your user agent? Works for me and that seems to be the only difference. Why change yours in the first place?

**Comment by JordieB** [comment]
Facebook locks down the account due to UA being too different, so I pulled and used my own. I tried the code again using the original UA and just authorized the code's UA, and it worked just fine, haha.

Thanks for entertaining my nonsense. I'll close this
