### ISSUE TITLE
Send any picture via Giphy

### ISSUE THREAD

**Issue by PoorBoyDaniel** [fbessez/Tinder#24]
All I want to do is send a picture of my choosing by following the guide at the following website 
https://medium.com/@calialec/swipe-left-on-tinder-s-security-sending-more-than-just-gifs-and-crashing-matches-phones-isn-t-ca21462f88be
I cannot, for the life of me figure out how to do this. I can find zero pertinent information to my query, and I don't even know if I should use the chrome developer console or an app like postman, please help. All I really need is a simple example of verbatim what you would put into the console or postman, with the link that I could replace. No amount of editing or trying his "example" worked and it always returned errors. I don't know what to leave out and what to include, I have spent 3 hours trying to figure it out with naught to show for it. I have absolutely no idea what or where this "config file" is that you spontaneously mention halfway through the documentation. Why didn't you make a tutorial, rather than information that is only useful to people who already know what they're doing, and probably don't need this information anyway.

**Comment by Mykke24** [comment]
I tried that too... but you cannot post your OWN gifs
they HAVE to be public gifs and non rated (there is a flag, if this is "r" Tinder won't display the gif)
