### ISSUE TITLE
Set username

### ISSUE THREAD

**Issue by Mykke24** [fbessez/Tinder#25]
Does someone know what the endpoint and JSON is to set the username programatically?

**Comment by fbessez** [comment]
Can you explain with examples what you mean? You can choose to set your username thru the command line? Check out argparse.

**Comment by Mykke24** [comment]
What you mean with argparse through command line? :D 
Well in the tinder app there is an option to set a username, you can browse it via browser then
www.gotinder.com/@YOURUSERNAME

this can be set in the app, but I cannot find the endpoint to set it via JSON

Example:
To hide the age you use {"hide_age":true} and the endpoint is https://api.gotinder.com/profile
but how to do that with the username?

**Comment by fbessez** [comment]
In order to do this, you would have to watch the requests that come from your phone. If you don't want to do that, you can also open up the Javascript Console 'Requests' Tab in Google Chrome when using the Tinder web client action that sets your username

**Comment by Mykke24** [comment]
If it would be that simple I would have done that ;)
You cannot set your web username via browser ONLY via the app.
A modified apk where I can mitm the request would be helpful but I cannot ssl unpin the current version.

**Comment by fbessez** [comment]
I don't have that. Best suggestion I could give is mitmproxy your phone traffic. That's how I got the rest of the api calls.

**Comment by Mykke24** [comment]
its encrypted though...

**Comment by fbessez** [comment]
It wasn't last time I checked. They must've upped their security. tough.. you could try hitting endpoints that you think would be the correct endpoint. maybe a POST to like /username?

**Comment by Mykke24** [comment]
the endpoint has to be /profile I am pretty sure
I tried several attempts, all with a code 200 but nothing changed though

when did you check the last time? the SSL is in the app since at least 2-3 years afaik

**Comment by fbessez** [comment]
I last checked in November 2017. https://stanfy.com/blog/monitor-mobile-app-traffic-with-sniffers/

**Comment by Mykke24** [comment]
I tried like 10x with Fiddler, never worked :)
but with Burp I had success
The endpoint is: https://api.gotinder.com/profile/username
and the requestBody: {"username":"yourusername"}

thanks for the help

**Comment by fbessez** [comment]
Awesome. Do you mind adding that function to features.py and updating the README and submitting a PR? If not, I’ll do it. But I figured you should st least get credit.

**Comment by Mykke24** [comment]
I am new to github. Dont know how to fork and submit it.
What is a PR?

btw... the HTTPMethod for setting a username is PUT
for deleting its DELETE without a requestbody but same endpoint

**Comment by fbessez** [comment]
PR is a pull request.

**Comment by Mykke24** [comment]
ok done :) 
I am not a python dev though
thats my first pyhton get and my first PR
bear with me ;)
