### ISSUE TITLE
v2 matches

### ISSUE THREAD

**Issue by tiarebalbi** [fbessez/Tinder#30]
New endpoint:
`/v2/matches?count=<SIZE || 60>&locale=<LANG>`

**Comment by fbessez** [comment]
Has this replaced the former endpoint? Or just another option?

**Comment by tiarebalbi** [comment]
Sorry about the leak of details. This endpoint is used on the web application to fetch the matches that you currently have.

**Comment by fbessez** [comment]
Cool -- I added it into `tinder_api.py`
