### ISSUE TITLE
Updates v1 is deprecated

### ISSUE THREAD

**Issue by jacob-cross99** [fbessez/Tinder#32]
Seems that you can't get updates from the API anymore...

**Comment by fbessez** [comment]
I'll check it out tonight and update it accordingly. thanks for the headsup

**Comment by jacob-cross99** [comment]
I have tried to fix this but I can't get updates through the API

**Comment by fbessez** [comment]
how do you mean it is deprecated? I just called my `get_updates` function and it worked just fine.

**Comment by fbessez** [comment]
GET `https://api.gotinder.com/updates` works just fine with the correct headers

**Comment by sebitoelcheater** [comment]
could you please provide those headers?

**Comment by fbessez** [comment]
```
headers = {
    'app_version': '6.9.4',
    'platform': 'ios',
    "content-type": "application/json",
    "User-agent": "Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)",
    "Accept": "application/json",
    "X-Auth-Token": YOURTOKENGOESHERE
}
```

**Comment by richardbell** [comment]
Hi, 
I keep getting an error when POSTing /updates: 
https://user-images.githubusercontent.com/4912072/46922248-df57e880-d00e-11e8-924c-e0ed6247bcb5.png . 
Any chance you can help me out with this?

**Comment by ptamas88** [comment]
I get the same error as @richardbell :(

**Comment by MaximKa99** [comment]
> I get the same error as @richardbell :(

It's working, you need to check your timestamp format. 
Java solution:
`SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.S'Z'");
Timestamp stamp = new Timestamp(120, 11, 20, 12, 12, 0, 0);
JsonNode node = mapper.readTree(service.getUpdates(format.format(stamp))).get("matches");`
