### ISSUE TITLE
Using accounts that aren't linked to FB

### ISSUE THREAD

**Issue by Tagge** [fbessez/Tinder#33]
Hi,
I would like to know if it was possible to use the API with accounts that have SMS auth instead of FB auth. I don't see it right now in the docs, so I guess it isn't yet available. I'm unable to sniff my phone's traffic because I've got an iPhone and no Mac, so I can't really dig into it. If someone can give me a clue on where to start, I'd gladly code something for it and push it forward. 
Thanks in advance,
Regards

**Comment by fbessez** [comment]
Are you sure that not having a Mac disallows you from monitoring traffic? 
I am sure it is possible and has a different auth flow -- but I have not seen it.

**Comment by Tagge** [comment]
I thought so because native tools are unavailable on Windows, but I've managed to set up a proxy just fine with Fiddler. I've got all the connection workflow decrypted, so I'll be able to push a pull request soon that adds SMS auth.
I've rarely seen people use FB to connect to Tinder in Europe, which I kinda understand considering all the controversy there has been recently.

**Comment by Tagge** [comment]
Support was added. Thanks to @fbessez for reviewing my commits and merging them !
