### ISSUE TITLE
403 Error on Like request

### ISSUE THREAD

**Issue by rostyslav-matushkin** [fbessez/Tinder#35]
I’ve an issue about 403 Forbidden error when I send like or pass request. This error appears for all other accounts. Who can help me? Thank.

**Comment by fbessez** [comment]
I'm gonna need more information from you if you're gonna get some help. What exactly are you doing? What is the exact error being shown? Did you authenticate through the process described?

**Comment by rostyslav-matushkin** [comment]
I tried to create new fb accounts and to use them to auth in Tinder by api method. When I send 'like' request via /like/_id, I get 403 error. It happens for each new account.
I've my main account, which was created a few months ago and this account can add 'likes' for any user.

**Comment by fbessez** [comment]
Are the Facebook accounts associated with a tinder profile already? Are they verified fb accounts? Not sure

**Comment by rostyslav-matushkin** [comment]
One fb account is associated with one tinder account on different proxy.
