### ISSUE TITLE
tinder_api_sms.py returns 401

### ISSUE THREAD

**Issue by florianmaxim** [fbessez/Tinder#38]
I succesfully received a tinder token running phone_auth_token.py
(maybe the default language could be changed to en btw).
I put the token in the config.py and commented all the facebook auth parameters out.
When I run get_recommendations() from from tinder_api_sms I get a 401.
Is this method not working anymore or am I doing anything wrong?
Thanks!

**Comment by fbessez** [comment]
@Tagge  any ideas?

**Comment by Tagge** [comment]
I’m taking a look into it, will keep this issue updated.

**Comment by bat553** [comment]
I recently test this script and i didn't receive a token but a 'onboarding_token'. 
I don't know if this is the subject of this issue but with the 'onboarding_token' I get a 400 error.
