### ISSUE TITLE
Very Simple Wrapper API in Node.js

### ISSUE THREAD

**Issue by florianmaxim** [fbessez/Tinder#39]
I just started wrapping this up in some kind of a very simple Node.js "Wrapper" API to make this even more accessible to more people. 
You just need a single line now to access your Tinder data.. Keep up the good work!
[https://github.com/florianmaxim/Tinder](https://github.com/florianmaxim/Tinder)

**Comment by jcrodriguez1989** [comment]
by the way, here is the R API https://github.com/jcrodriguez1989/Rtinder. Which is basically an R translation of the Python API.
