### ISSUE TITLE
Phone Number Auth possible?

### ISSUE THREAD

**Issue by idevsoftware** [fbessez/Tinder#4]
Hi,

Thanks for your great work. Do you know if is there any way to acquire a session token by simulating the phone number/sms sign up mechanism used by the official Tinder App? It makes use of Facebook's Account Kit? If so, would it invalidate the existing session from the official App?

**Comment by programista18k** [comment]
I had to write an android app to try this, got ID and token, but they are refused with 401 all the time.

**Comment by fbessez** [comment]
Hey guys, sorry but I am not really looking at this anymore. Got sidetracked. If there is a will there is a way but it seems that Tinder has been beefing up security lately.
