### ISSUE TITLE
tinder_api.get_auth_token

### ISSUE THREAD

**Issue by hp-supplies-online-marketing** [fbessez/Tinder#43]
Hey

just wondering if there are any troubleshooting ideas for the tinder_api.get_auth_token() function?
its throwing the default exception 

No JSON object could be decoded
{'error': 'Something went wrong. Sorry, but we could not authorize you.'}

successfully got fb_access_token and fb_user_id but when I pass them to the get_auth_token function it fails.

Any ideas of troubleshooting ideas?

**Comment by paulgibbonshp** [comment]
I updated FB_AUTH = "https://www.facebook.com/v2.8/dialog/oauth? in fb_auth_token.py but no luck.

**Comment by fbessez** [comment]
It might be that it’s a different endpoint as well. I’d recommend putting a break point after the error in the code and before the default message is returned so you get better info on why it’s failing.

**Comment by mafa89** [comment]
it gives 
{u'error_no': 40304, u'code': 403, u'error': u'minimum client version enforced#MINIMUM_VERSION_REQUIRED'}
