### ISSUE TITLE
get_auth_token closes facebook account

### ISSUE THREAD

**Issue by PaulAhuevo** [fbessez/Tinder#47]
When I try to use the script for getting the auth-token with robobrowser facebook closes the account due to suspicious activity.

Anyone else experiencing the problem and knows how to solve it?

**Comment by VictorLM** [comment]
For me, it's happen only when i try to run the script into my Linux VPS using CRON daily. When I run the script manually on my desktop, i get the token and my FB account keeps normal.

**Comment by barrypearseburke** [comment]
same issue here.

**Comment by kodingkirby** [comment]
It usually happens when I run it from an AWS in a region other than the one I normally use.
Usually, a quick login to the browser confirming the 'suspicious' activity is enough to get it working again.
