### ISSUE TITLE
Unsupported client version

### ISSUE THREAD

**Issue by igornazarov1991** [fbessez/Tinder#5]
Hello.

"Get match recommendations" https://api.gotinder.com/user/recs request does not work for me. Http headers are the next:

[httpHeaders setObject:self.tinderToken forKey:@"X-Auth-Token"];
[httpHeaders setObject:@"application/json" forKey:@"Content-type"];
[httpHeaders setObject:@"Tinder/4.7.1 (iPhone; iOS 9.2; Scale/2.00)" forKey:@"User-agent"];

Response is the next:

{
    message = "unsupported client version";
}

After that I checked how a similar application performs this request using Charles sniffer. They use different url:

https://api.gotinder.com/recs/core?locale=ua

and https headers are the next:

[httpHeaders setObject:self.tinderToken forKey:@"X-Auth-Token"];
[httpHeaders setObject:@"application/json" forKey:@"Content-type"];
[httpHeaders setObject:@"Tinder Android Version 7.0.0" forKey:@"User-agent"];
[httpHeaders setObject:@"ios" forKey:@"platform"];
[httpHeaders setObject:@"23" forKey:@"os-version"];
[httpHeaders setObject:@"2117" forKey:@"app-version"]; 

I this case it seems they banned me:

{
    error = banned;
    status = 403;
}

I am not sure what exactly they ban (user, ip, ...). But I tried another Facebook account - result is the same. Also tried to connect from another ip and result is the same. In same time /updates and /user/_id requests work fine. 

Can you please take a look and check? Thanks in advance, Igor.

**Comment by fbessez** [comment]
Hey @igornazarov1991, 

Sorry for the late response. I had some other projects to work on. I have updated the client version so perhaps this solves your problem. Let me know!

**Comment by dbof10** [comment]
I got an error. It seems like the API changed
```Traceback (most recent call last):
  File "main.py", line 9, in <module>
    main()
  File "main.py", line 4, in main
    matches = api_client.get_match_info()
  File "/Users/daniel/Downloads/Tinder-master/features.py", line 19, in get_match_info
    matches = api.get_updates()['matches']
KeyError: 'matches'

```

**Comment by fbessez** [comment]
@dbof10 Hey, I do not get this error when I run api.get_updates()['matches']. Do you mind telling me what specifically you did to get this error?

**Comment by dbof10** [comment]
hey I'm not from python world. I don't know how to use your code. `python features.py` prints empty for me

**Comment by dbof10** [comment]
I'm getting this instead 
`An exception of type KeyError occurred. Arguments:
('bio',)`

**Comment by fbessez** [comment]
Yeah it's not supposed to really print anything. It is supposed to store data in the match_info variable. so just do `python3 -i features.py` and then type `match_info` and it should print then @dbof10

**Comment by dbof10** [comment]
Works for me. Thanks

**Comment by dbof10** [comment]
Do you have any idea for getting notified for a new message?

**Comment by ozgunozankilic** [comment]
It may not be a direct solution, but you could run get_updates() at intervals to check if there's something new. You could store the timestamp from the last time you checked and use it as the "last_activity_date" maybe? Then, it could trigger some desktop notification or something using another library.

**Comment by fbessez** [comment]
Yes @ozgunozankilic, I believe that is how Tinder does notifications as well.
