### ISSUE TITLE
#INVALID_APP_ID@auth_handlers_facebook.getIdByToken}

### ISSUE THREAD

**Issue by Ameeraarif123** [fbessez/Tinder#54]
{
    "code": 401,
    "error": "Invalid App ID 302914573649600#INVALID_APP_ID@auth_handlers_facebook.getIdByToken}",
    "error_no": 87401
}

when i am trying to login with tinder with api  https://api.gotinder.com/auth 
by giving valid token and fb id it show this erro. please help me to rectify this issue

**Comment by Ameeraarif123** [comment]
any one can help on this please

**Comment by VineeshaV** [comment]
I'm also getting the same error, Please anyone help me on this

**Comment by enric1994** [comment]
Is the API outdated due to a Tinder update? How I am supposed to find a girlfriend?😢

**Comment by enric1994** [comment]
Nevermind, it is working for me.
The problem was that after some time using the API, I needed to access Tinder through Facebook (they verified my number). After that, all OK.
