### ISSUE TITLE
/user/matches/_id

### ISSUE THREAD

**Issue by lintangtimur** [fbessez/Tinder#56]
when i try to send message to specific Id with this payload
```json
{
	"message":"hi test dude"
}
```
output
```
{
    "status": "404",
    "error": ""
}
```

**Comment by joyahm** [comment]
> _id
Is it user id or match id?
You should provide match id here, match id is combination of both (sender & recipients user id).

**Comment by brunetton** [comment]
Same here :(

I never used this API endpoint before so I can't tell if it "stopped working" but as far as I see, it doesn't seems to work. 

`/matches/{match id}` works fine howether.

**Comment by brunetton** [comment]
Strangely this works in certain circumstances. I've the feeling that it should have something to do with facebook token; don't know
