### ISSUE TITLE
How do you get tinder share link of profile

### ISSUE THREAD

**Issue by Kreijstal** [fbessez/Tinder#59]
Tinder app allows you to share users and they have some short url with their name on it, how can you access this link from the api?

**Comment by romkazor** [comment]
Anybody?

**Comment by markshapiro** [comment]
@Kreijstal @romkazor

**Comment by markshapiro** [comment]
@Kreijstal @romkazor 
https://api.gotinder.com/user/532863edb9e799481b00081f/share

**Comment by sank69** [comment]
Screenshot the profile and a notification type window pop up on top click on it and share
