### ISSUE TITLE
Missing config? ImportError: No module named 'config'

### ISSUE THREAD

**Issue by santafebound** [fbessez/Tinder#6]
What's the deal here?

$ python features.py
Traceback (most recent call last):
  File "features.py", line 7, in <module>
    import config
ImportError: No module named 'config'

```
pip install config
```

Sorry I haven't used Python in a while so I totally forgot about pip.

**Comment by santafebound** [comment]
```
$ python features.py
Traceback (most recent call last):
  File "features.py", line 7, in <module>
    import config
  File "C:\Python34\lib\site-packages\config.py", line 733
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Well that's not good. I'm using Python3 so not sure what's up here.

Am I meant to replace``import config`` with ``tinder_config_ex``?

**Comment by ozgunozankilic** [comment]
"tinder_config_ex.py" says:

> # Your real config file should simply be named "config.py"

So rename that file to "config.py".

**Comment by fbessez** [comment]
Yea, thanks @ozgunozankilic. 

@santafebound You must write your own file called config.py that has all of your specific usernames and passwords.

**Comment by santafebound** [comment]
@ozgunozankilic @fbessez Gotcha! Have it all working now. Thanks.
