### ISSUE TITLE
like() returns error 400

### ISSUE THREAD

**Issue by brunetton** [fbessez/Tinder#63]
Hi,

I just tried this great project and I'm very exited about :) But a little problem appeared, after a successful auth (and [some config](https://stackoverflow.com/a/16630836/276894) to display requests details):

```python
In [33]: tinder_api.like("583b4a3be6230d9d08761381")
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.gotinder.com
send: 'GET /like/583b4a3be6230d9d08761381 HTTP/1.1\r\nHost: api.gotinder.com\r\napp_version: 6.9.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json\r\nX-Auth-Token: xxxxx-xxxxxx-xxxxxx\r\nplatform: ios\r\nConnection: keep-alive\r\nUser-agent: Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)\r\ncontent-type: application/json\r\n\r\n'get_person
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Content-Type: application/json; charset=utf-8
header: Date: Fri, 15 Feb 2019 01:14:37 GMT
header: X-Request-ID: b8tqs3k7qpju5afs8gg0
header: Content-Length: 42
header: Connection: keep-alive
DEBUG:requests.packages.urllib3.connectionpool:"GET /like/583b4a3be6230d9d08761381 HTTP/1.1" 400 42
Out[33]: {u'error': u'malformed request', u'status': 400}
```

In the other hand, `tinder_api.get_person("583b4a3be6230d9d08761381")` works well. `get_meta()`, `get_self()` works too.

**Comment by cdangerdouglas** [comment]
after using paul-at's commit, i am faced with this is the json response from the like function:
{
    "X-Padding": "{*meta*:{*code*:200,*requestId*:*59a45921351e3d43b07028b5*},*response*:{*venue*:{*id*:*412d2800f964a520df0c1fe3*,*name*:*Central Park*,*contact*:{*phone*:*2123106600*,*formattedPhone*:*(212) 310-6600*,*twitter*:*centralparknyc*,*instagram*:*centralparknyc*,*facebook*:*37965424481*,*facebookUsername*:*centralparknyc*,*facebookName*:*Central Park*},*location*:{*address*:*59th St to 110th St*,*crossStreet*:*5th Ave to Central Park West*,*lat*:40.78408342593807,*lng*:-73.96485328674316,*postalCode*:*10028*,*cc*:*US*,*city*:*New York*,*state*:*NY*,*country*:*United States*,*formattedAddress*:[*59th St to 110th St (5th Ave to Central Park West)*,*New York, NY 10028*,*United States*]},*canonicalUrl*:*https://foursquare.com/v/central-park/412d2800f964a520df0c1fe3*,*categories*:[{*id*:*4bf58dd8d48988d163941735*,*name*:*Park*,*pluralName*:*Parks*,*shortName*:*Park*,*icon*:{*prefix*:*https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_*,*suffix*:*.png*},*primary*:true}],*verified*:true,*stats*:{*checkinsCount*:364591,*usersCount*:311634,*tipCount*:1583,*visitsCount*:854553},*url*:*http://www.centralparknyc.org*,*likes*:{*count*:17370,*summary*:*17370 Likes*},*rating*:9.8,*ratingColor*:*00B551*,*ratingSignals*:18854,*beenHere*:{*count*:0,*unconfirmedCount*:0,*marked*:false,*lastCheckinExpiredAt*:0},*photos*:{*count*:26681,*groups*:[{*type*:*venue*,*name*:*Venue photos*,*count*:26681,*items*:[{*id*:*513bd223e4b0e8ef8292ee54*,*createdAt*:1362874915,*source*:{*name*:*Instagram*,*url*:*http://instagram.com*},*prefix*:*https://igx.4sqi.net/img/general/*,*suffix*:*/655018_Zp3vA90Sy4IIDApvfAo5KnDItoV0uEDZeST7bWT-qzk",
    "likes_remaining": 100,
    "match": false
}


every call to the like function produces this same output.

**Comment by ozetadev** [comment]
Don’t include your phone number 🤦‍♂️

**Comment by cdangerdouglas** [comment]
My phone number is not in there. That is maybe the phone number for Central Park?
Im not sure what this response is.

**Comment by brunetton** [comment]
@paul-at https://github.com/fbessez/Tinder/pull/64 solves the problem

**Comment by romkazor** [comment]
@brunetton Is tinder_api.get_person() still works?
