### ISSUE TITLE
Actual API

### ISSUE THREAD

**Issue by romkazor** [fbessez/Tinder#66]
Hello, where can i find actual methods of API?
Thanks

**Comment by therealscottcarlow** [comment]
This is the actual API (or what's been discovered of it), there are just no official docs; ostensibly to prevent bot creation, though at this point it's fairly obvious that obscurity wasn't the right choice for that.

**Comment by RMatushkin** [comment]
I've open-sourced my own library written on Java where you can find all basic requests including authorization and registration via SMS: https://github.com/RMatushkin/tinder-api
