### ISSUE TITLE
receiving the following error when excluding content type in get request for like

### ISSUE THREAD

**Issue by MHilhorst** [fbessez/Tinder#67]
after using paul-at's commit, i am faced with this is the json response from the like function:
{
    "X-Padding": "{*meta*:{*code*:200,*requestId*:*59a45921351e3d43b07028b5*},*response*:{*venue*:{*id*:*412d2800f964a520df0c1fe3*,*name*:*Central Park*,*contact*:{*phone*:*2123106600*,*formattedPhone*:*(212) 310-6600*,*twitter*:*centralparknyc*,*instagram*:*centralparknyc*,*facebook*:*37965424481*,*facebookUsername*:*centralparknyc*,*facebookName*:*Central Park*},*location*:{*address*:*59th St to 110th St*,*crossStreet*:*5th Ave to Central Park West*,*lat*:40.78408342593807,*lng*:-73.96485328674316,*postalCode*:*10028*,*cc*:*US*,*city*:*New York*,*state*:*NY*,*country*:*United States*,*formattedAddress*:[*59th St to 110th St (5th Ave to Central Park West)*,*New York, NY 10028*,*United States*]},*canonicalUrl*:*https://foursquare.com/v/central-park/412d2800f964a520df0c1fe3*,*categories*:[{*id*:*4bf58dd8d48988d163941735*,*name*:*Park*,*pluralName*:*Parks*,*shortName*:*Park*,*icon*:{*prefix*:*https://ss3.4sqi.net/img/categories_v2/parks_outdoors/park_*,*suffix*:*.png*},*primary*:true}],*verified*:true,*stats*:{*checkinsCount*:364591,*usersCount*:311634,*tipCount*:1583,*visitsCount*:854553},*url*:*http://www.centralparknyc.org*,*likes*:{*count*:17370,*summary*:*17370 Likes*},*rating*:9.8,*ratingColor*:*00B551*,*ratingSignals*:18854,*beenHere*:{*count*:0,*unconfirmedCount*:0,*marked*:false,*lastCheckinExpiredAt*:0},*photos*:{*count*:26681,*groups*:[{*type*:*venue*,*name*:*Venue photos*,*count*:26681,*items*:[{*id*:*513bd223e4b0e8ef8292ee54*,*createdAt*:1362874915,*source*:{*name*:*Instagram*,*url*:*http://instagram.com*},*prefix*:*https://igx.4sqi.net/img/general/*,*suffix*:*/655018_Zp3vA90Sy4IIDApvfAo5KnDItoV0uEDZeST7bWT-qzk",
    "likes_remaining": 100,
    "match": false
}

every call to the like function produces this same output.

_Originally posted by @cdangerdouglas in https://github.com/fbessez/Tinder/issues/63#issuecomment-467690364_

**Comment by Pau1fitz** [comment]
I believe that they may be doing this for [security reasons](https://security.stackexchange.com/questions/7738/should-i-include-a-random-padding-in-every-https-request-and-response) to prevent the decryption of HTTP traffic. The details of the response that you are interested in should be above this in the response, and should look something like this:

```
"match": true,
"likes_remaining": 12,
```
