### ISSUE TITLE
code":400,"error":"Missing authToken#NO_FB_TOKEN","error_no":40001

### ISSUE THREAD

**Issue by santafebound** [fbessez/Tinder#7]
>     $ curl -X POST 
>             -H "X-Auth-Token: FB_AUTH_TOKEN" \
>             -H "Content-type: application/json" \
>             -H "User-agent: Tinder/7.5.3 (iPhone; iOS 10.3.2; Scale/2.00)" \
>     https://api.gotinder.com/auth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    69  100    69    0     0    105      0 --:--:-- --:--:-- --:--:--   105{"code":400,"error":"Missing authToken#NO_FB_TOKEN","error_no":40001}

I'm just trying out the first command, to get authentication but it's not working. Am I using the incorrect Facebook Auth Token? Does my curl command look correct?

**Comment by ozgunozankilic** [comment]
I couldn't manage to get a working token too. Whenever I try to get a token or use features, Facebook informs me about Tinder accessing my account (so there shouldn't be a problem about my credentials), but it seemingly fails to get a working token.

**Comment by santafebound** [comment]
I figured it out. Run the fb_auth_token.py script independently.

`python -c 'import fb_auth_token; print fb_auth_token.get_fb_access_token("facebookEmail@asdf.com", "facebookPass")'`
