### ISSUE TITLE
No connection adapters were found get_fb_access_token

### ISSUE THREAD

**Issue by bbsmithy** [fbessez/Tinder#75]
No connection adapters were found for 'fb464891386855067://authorize/#granted_scopes=user_birthday%2Cuser_l........

I'm getting the above error when running latest get_fb_access_token(email, password)
The same code what work fine before to do this. I am running the function in isolation to test it so its nothing that I have changed.

Is anyone else getting this problem?

```
def get_fb_access_token(email, password):
    s = robobrowser.RoboBrowser(user_agent=MOBILE_USER_AGENT, parser="lxml")
    s.open(FB_AUTH)
    f = s.get_form()
    f["pass"] = password
    f["email"] = email
    s.submit_form(f)
    f = s.get_form()
    try:
        s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])
        access_token = re.search(
            r"access_token=([\w\d]+)", s.response.content.decode()).groups()[0]
        return access_token
    except Exception as ex:
        print("access token could not be retrieved. Check your username and password.")
        print("Official error: %s" % ex)
        return {"error": "access token could not be retrieved. Check your username and password."}

```

**Comment by mc51** [comment]
Yes, I get the same.

**Comment by TheButlah** [comment]
Same issue here

**Comment by bbsmithy** [comment]
https://github.com/jcrodriguez1989/Rtinder/commit/290d60b784ef929722d56db5d7f9de3d7ac4f5bf
Issue was fixed in Tinder library written in R. Looks like searching for accessToken in headers of response

**Comment by FelixLabelle** [comment]
The problem is that facebook doesn't send back a URL robobrowser can handle. I'm working on a more legit fix, but I've found a hacky work around for now.

`
		try:
			browser.submit_form(form, submit=form.submit_fields['__CONFIRM__'])
			self.access_token = re.search(
				r"access_token=([\w\d]+)", browser.response.content.decode()).groups()[0]
		except requests.exceptions.InvalidSchema as browserAddress:
			#print(type(browserAddress))
			self.access_token = re.search(
				r"access_token=([\w\d]+)",str(browserAddress)).groups()[0]
`

**Comment by EralpB** [comment]
Thanks for sharing, I think this solution is good enough, anything you do with a non-public API is "hacky" anyway.

I noticed there is a redirect_url field in the form before submitting, if we changed this to facebook.com or removed it completely maybe it will just work, but I don't think anything is less hacky haha.

**Comment by philipperemy** [comment]
@FelixLabelle you're awesome!

**Comment by yingalive** [comment]
I changed the script as FelixLabelle suggested (not sure i'm doing the right way, quite new to python) and i got the returned result of token and fb_id, but still can not be authorized. Very much appreciate if someone could shed some light.

`
def get_fb_access_token(email, password):
    s = robobrowser.RoboBrowser(user_agent=MOBILE_USER_AGENT, parser="lxml")
    s.open(FB_AUTH)
    f = s.get_form()
    f["pass"] = password
    f["email"] = email
    s.submit_form(f)
    f = s.get_form()


    try:
        s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])
        #print(browser.response.content.decode())
        access_token = re.search(
            r"access_token=([\w\d]+)", s.response.content.decode()).groups()[0]
        return access_token
    except requests.exceptions.InvalidSchema as browserAddress:
        #print(type(browserAddress))
        access_token = re.search(
            r"access_token=([\w\d]+)",str(browserAddress)).groups()[0]
        return access_token
`

`

from tinder_api import *;
from fb_auth_token import *;

host = 'https://api.gotinder.com'

# Enter your facebook email
fb_username = 'FB_email'
# Enter your facebook password
fb_password = 'FB_pin'

fb_access_token = get_fb_access_token(fb_username, fb_password)
fb_user_id = get_fb_id(fb_access_token)

print(fb_access_token)
print(fb_user_id)

print(get_auth_token(fb_access_token,fb_user_id))
# authverif()
`

returned as:
`
#token values that i changed to some dummy values, looks like this 
EGBBGm0PX4ZDpsBAINhoWZCm91nSkmgIye1kOdbmkV0893soL69CAUpsLFgmDDbVWeZCj1iaOwhy196n4OnvPzWNquk1uHKR0WYnPuRzyM2EGUNMDyFOIHsjVSic6pGVsIbJAvk2cqIjwWCC3DqLlliHmMZAVRR6SycZABAphj0Iy4QZDZD
#FB id that i changed to some dummy values, looks like this
1590251234524230
Expecting value: line 1 column 1 (char 0)
{'error': 'Something went wrong. Sorry, but we could not authorize you.'}
`

**Comment by lritter79** [comment]
I'm still getting the same error as @yingalive
