### ISSUE TITLE
Get Recommendations Timeout

### ISSUE THREAD

**Issue by mc51** [fbessez/Tinder#76]
After swiping through all recommendations I'm trying to get new ones.
However, this fails.
Requesting  `/v2/recs/core?locale=` I get this response:
{'meta': {'status': 200}, 'data': {'timeout': 1800000}}

Requesting `/user/recs` I get this response: 
{'message': 'recs timeout'}

After logging in to tinder.com with a browser, I also don't get any recommendations anymore. However, when I change the distance setting in my profile and return to swiping in the browser I once again get new recommendations. But this doesn't affect anything in the API client. 

Anybody figured this out?

**Comment by maxie-max** [comment]
Have the same issue 

Requesting https://api.gotinder.com/user/recs
```
{
    "message": "recs timeout"
}
```
