### ISSUE TITLE
Avoiding timeout on SMS login

### ISSUE THREAD

**Issue by liam923** [fbessez/Tinder#77]
Is there a known way to avoid having to get a new token every 24 hours when using SMS verification? Obviously the app is capable of avoiding this, but I cannot find any documentation or examples that show how to.

**Comment by mc51** [comment]
With your SMS Auth token (the one you get from `https://graph.accountkit.com/v1.2/start_login?[...]` you should be able to get an Tinder-Token / X-Auth-Token without any user interaction. The SMS Auth token should be valid for either 60 or 90 days (the documentation is not really clear for me on this). So after getting the SMS Auth Token you should save it, i.e. to your config file. Then, you could just get an X-Auth-Token every 24h (or whenever it expires). You need to change the code, maybe this gets you started (notice that I've changed quite a bit of the code from the master branch, so you will need to adapt it): 

```
    def get_auth_token_sms(self, sms_auth_token):
        """Gets the Tinder SMS Auth Token and Refresh token
        """
        endpoint = '/v2/auth/login/accountkit'
        params = {
            'token': sms_auth_token
        }
        res = self.post_request(endpoint, params)
        auth_token = res.get('data', {}).get('api_token')
        refresh_token = res.get('data', {}).get('refresh_token')
        return auth_token, refresh_token
```
