### ISSUE TITLE
Getting working _id from /fast-match/teasers

### ISSUE THREAD

**Issue by Mattesackboy** [fbessez/Tinder#78]
By sending a request to https://api.gotinder.com/v2/fast-match/teasers I get all Users that liked me, but ids are written like this: bf9a5a21-7dbd-4be8-accd-b48dd79b295e and not like MongoDB ObjectIDs (ex: 5d0fc0526fd67815008cb7fb)
How can I get the correct _id to then send a request to /like endpoint?

**Comment by ReDDarKwh** [comment]
+1

**Comment by ScottXTra** [comment]
I think that's the point. Tinder does not give you the real Id or any other data so apis cant be made to get tinder gold services without paying

**Comment by cadatoiva** [comment]
Well, the image IDs seem to be the same between the two APIs, That might be a hint towards cross matching. We'd either need someone who already has premium to see what the difference in data between paid/free accounts, or data from a found match that's in this like data.
