### ISSUE TITLE
Auth OK but no json available

### ISSUE THREAD

**Issue by simonprovost** [fbessez/Tinder#79]
Hello,

First and foremost, thanks for your github it is very helpful !! So, I've tried many things to just run your script but nothing well happened.

` [+] Trying to authenticate you...`
`OK //this is the output content of the python requests "print connexion_response.content"`
`\Error : No JSON object could be decoded`

I've always this, I've tried something but nothing, could you help me please ?

**Comment by eriakul** [comment]
I've hit this issue as well. Have you made any progress?
