### ISSUE TITLE
/matches/{match id}

### ISSUE THREAD

**Issue by santafebound** [fbessez/Tinder#8]
I can get a specific match after scouring through an array of recommendations, but can I get a list of my current matches somehow? What's the correct endpoint for that?

/matches/ alone doesn't work.

**Comment by fbessez** [comment]
Hey @santafebound ,

check out the get_updates function. that's the call you're going to want to make.

**Comment by santafebound** [comment]
I see that the python function will return matches based on last activity date, but would you know if a direct curl command could also retrieve this same information?

**Comment by fbessez** [comment]
curl -i -H "Accept: application/json" -H "Content-Type: application/json" http://hostname/resource
yea just put in the appropriate headers and endpoint and it should work for a simple GET request like get_updates
