### ISSUE TITLE
Error on tinder 403

### ISSUE THREAD

**Issue by Edward1123** [fbessez/Tinder#81]
I’ve an issue about 403 Forbidden error when I send like or pass request. I need some help please. Thank you!

**Comment by zbeucler2018** [comment]
I got the same 403 Forbidden error when I tried a "user/rec" request

**Comment by killvung** [comment]
Have you included the required `X-Auth-Token` in your header? 
https://github.com/fbessez/Tinder#required-headers
If not you have to request one through facebook authentication
https://github.com/fbessez/Tinder#config-file
