### ISSUE TITLE
API for "Boost"?

### ISSUE THREAD

**Issue by amytan35** [fbessez/Tinder#9]
Did you figure out how to activate the "Boost" feature ?

thanks

**Comment by ozgunozankilic** [comment]
Before updating the status, probably some third-party stuff come into play to check the payment and stuff. So, I don't think you can achieve that using the API.

**Comment by amytan35** [comment]
hmmm.... Why/how is this different than super-likes? (assume authenticated user has TP).

**Comment by ozgunozankilic** [comment]
Oh, sorry, I thought you were asking for a regular user. I've never used that feature, but if it works by manual activation, then it probably uses the API, you're right.

**Comment by fbessez** [comment]
Hey @amytan35 , 

I don't have a Tinder Plus account, but if I did I would use Burp Suite to proxy my phone's requests when using the Tinder app. Then you can see which endpoints are being used and what data is being passed when you interact with the native Tinder app. Then you can extrapolate the API from that.
