### ISSUE TITLE
Requesting token via sms is not working

### ISSUE THREAD

**Issue by IvSan** [fbessez/Tinder#95]
`send_code` in `phone_auth_token.py` is not working any more.
If make a manual request using `CODE_REQUEST_URL`, an error got back:
```
{
    "error": {
        "message": "SMS is currently unavailable. Please use a different login method or update the app and try again.",
        "type": "OAuthException",
        "code": 15019,
        "error_subcode": 1948016,
        "is_transient": false,
        "error_user_title": "SMS is currently unavailable.",
        "error_user_msg": "SMS is currently unavailable. Please use a different login method or update the app and try again.",
        "fbtrace_id": "A5peRSDpTKhJcp_0fiMawuD"
    }
}
```
Looks like sms token API has changed.

**Comment by mc51** [comment]
I can confirm this. I get the following:

`
tinderbot.utils - ERROR - Could not request SMS-Code for Access token - Code: 400 - Error: {"error":{"message":"SMS is currently unavailable. Please use a different login method or update the app and try again.","type":"OAuthException","code":15019,"error_subcode":1948016,"is_transient":false,"error_user_title":"SMS is currently unavailable.","error_user_msg":"SMS is currently unavailable. Please use a different login method or update the app and try again.","fbtrace_id":"AcTXTOh4ugMXsBxviCRyidc"}}
`

**Comment by IvSan** [comment]
Solved with https://github.com/fbessez/Tinder/pull/90
